file_format: "1"
id: piano
name: The Piano
type: shield
url: https://github.com/benvallack/zmk-config-piano
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - piano_dongle_left
  - piano_dongle_right
  - piano_dongle
  - piano_norm_left
  - piano_norm_right
