file_format: "1"
id: piano
name: The Flame 
type: shield
url: https://github.com/benvallack/zmk-config-piano
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - piano_left
  - piano_right
  - piano_dongle
